// <auto-generated />
using CharacterCreator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterCreator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterCreator.Data.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("BirthLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterAge")
                        .HasColumnType("int");

                    b.Property<string>("CharacterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("WarriorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            BirthLocation = "Elysium",
                            CharacterAge = 73,
                            CharacterDescription = "Very fast man",
                            CharacterName = "Rigo",
                            TeamId = 1,
                            WarriorType = "Paladin"
                        },
                        new
                        {
                            CharacterId = 2,
                            BirthLocation = "Xandu",
                            CharacterAge = 12,
                            CharacterDescription = "Very stronk man",
                            CharacterName = "Ali",
                            TeamId = 1,
                            WarriorType = "Barbarian"
                        },
                        new
                        {
                            CharacterId = 3,
                            BirthLocation = "Valhallf",
                            CharacterAge = 7341,
                            CharacterDescription = "Very wise man",
                            CharacterName = "Ryan",
                            TeamId = 2,
                            WarriorType = "Sorcerer"
                        },
                        new
                        {
                            CharacterId = 4,
                            BirthLocation = "Indianapolis",
                            CharacterAge = 35,
                            CharacterDescription = "Very scary man",
                            CharacterName = "Terry",
                            TeamId = 2,
                            WarriorType = "Assassin"
                        },
                        new
                        {
                            CharacterId = 5,
                            BirthLocation = "The Holler",
                            CharacterAge = 55,
                            CharacterDescription = "Very dumb but coo man",
                            CharacterName = "Jimbob",
                            TeamId = 3,
                            WarriorType = "Druid"
                        },
                        new
                        {
                            CharacterId = 6,
                            BirthLocation = "A regular place",
                            CharacterAge = 30,
                            CharacterDescription = "Just a regular dude",
                            CharacterName = "Regular Joe",
                            TeamId = 3,
                            WarriorType = "Regular Dude"
                        });
                });

            modelBuilder.Entity("CharacterCreator.Data.Entities.FeatureEntity", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Ability = "Dexterity",
                            BodyType = "Slender",
                            CharacterId = 1,
                            EyeColor = "Purple",
                            HairColor = "Green",
                            HairStyle = "Perm",
                            Height = "7ft 3in",
                            SkinColor = "Fair",
                            Weight = "150lb"
                        },
                        new
                        {
                            FeatureId = 2,
                            Ability = "Strength",
                            BodyType = "Slim",
                            CharacterId = 2,
                            EyeColor = "Red",
                            HairColor = "Red",
                            HairStyle = "Spiked",
                            Height = "6ft 1in",
                            SkinColor = "Light",
                            Weight = "180lb"
                        },
                        new
                        {
                            FeatureId = 3,
                            Ability = "Wisdom",
                            BodyType = "Rotund",
                            CharacterId = 3,
                            EyeColor = "Pink",
                            HairColor = "Not applicable",
                            HairStyle = "Bald",
                            Height = "5'10",
                            SkinColor = "Fair-Dark",
                            Weight = "600lb"
                        },
                        new
                        {
                            FeatureId = 4,
                            Ability = "Stealth",
                            BodyType = "Athletic",
                            CharacterId = 4,
                            EyeColor = "Brown",
                            HairColor = "Brown",
                            HairStyle = "Short",
                            Height = "6feet 3in",
                            SkinColor = "Fair-Light",
                            Weight = "200"
                        },
                        new
                        {
                            FeatureId = 5,
                            Ability = "Healing",
                            BodyType = "Petite",
                            CharacterId = 5,
                            EyeColor = "Blue",
                            HairColor = "Blue",
                            HairStyle = "Long Hair",
                            Height = "4feet 12in",
                            SkinColor = "Very Dark",
                            Weight = "100lb"
                        },
                        new
                        {
                            FeatureId = 6,
                            Ability = "Regularness",
                            BodyType = "Rotund",
                            CharacterId = 6,
                            EyeColor = "Yellow",
                            HairColor = "Yellow",
                            HairStyle = "Mullet",
                            Height = "5feet 5in",
                            SkinColor = "Very Light",
                            Weight = "400lb"
                        });
                });

            modelBuilder.Entity("CharacterCreator.Data.Entities.TeamEntity", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.Property<string>("TeamSlogan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CharacterId = 0,
                            TeamDescription = "They really aren't very cool",
                            TeamMission = "Chyllin",
                            TeamName = "Kool Kids",
                            TeamNumber = 17,
                            TeamSlogan = "To Infinity And Beyond!"
                        },
                        new
                        {
                            TeamId = 2,
                            CharacterId = 0,
                            TeamDescription = "This team is not very effective",
                            TeamMission = "Not Failing",
                            TeamName = "The Losers",
                            TeamNumber = 0,
                            TeamSlogan = "FBGM"
                        },
                        new
                        {
                            TeamId = 3,
                            CharacterId = 0,
                            TeamDescription = "Everyone aspires to be them",
                            TeamMission = "World Domination",
                            TeamName = "Chads",
                            TeamNumber = 69,
                            TeamSlogan = "Send It!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
